-- Billing/auth persistence foundation for DEFRAG.

create table if not exists public.billing_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text unique,
  current_plan text not null default 'free',
  subscription_state text not null default 'none',
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_subscription_id text not null unique,
  plan text not null,
  state text not null,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);

create table if not exists public.processed_webhook_events (
  event_id text primary key,
  processed_at timestamptz not null default now()
);

alter table public.billing_accounts enable row level security;
alter table public.subscriptions enable row level security;
alter table public.processed_webhook_events enable row level security;

-- Users can read their own billing/account records.
do $$ begin
  create policy "billing_accounts_select_own" on public.billing_accounts
    for select using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "subscriptions_select_own" on public.subscriptions
    for select using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
